### ISSUE TITLE
Gryo Data Returning all zeros

### ISSUE THREAD

**Issue by mjs513** [kriswiner/Teensy_Prop_Shield#3]
Hi Kris

I am trying to sort out some issues with the prop-shield's gyro so I found a reference to your sketch in the teensy forum so I figured I would try a second approach vs Pauls nxpsense lib. 

Now to the problem.  I loaded it no issue it did the calibration but all the gyro data returns zero.  Its like the data ready is never tripped.  I put a few print statements in the gyro read function but it never does the read. Do I need to slow down the sample rates? Think I saw it set at 200.

Any help would be appreciated

**Comment by kriswiner** [comment]
Hi Mike,

Are you saying you always get zeroes returned fro the gyro data or just the
gyro calibration? In either case, yes, you can verify what the raw register
reads are returning. If zero, then there is some kind of data ready problem.
You can also just comment out the data ready test and see if you can read
anything from the gyro.

I haven't had any trouble with this. I'll test it again though.

I just downloaded the two files from github, and compiled and ran with my prop shield. I get non-zero gyro values and the IMUs seem to be working well.

Maybe you have a faulty Prop Shield?

Kris

-----Original Message-----

**Comment by mjs513** [comment]
Kris.  Did the first part and on the calibration side it was just returning 0, 512, 512's for all the reads.  Just deleted the DR test and all it is returning is 512, 512, and 0 for gx, gy and gz.

Has to be me but not sure where the problem is unless the gyro went.  Although I am having a problem with the gryo in general.  Have one connected to a mega and it just seems very unstable.  Just did a post on that to the forum.

By the way I picked up the lsm9ds1 from tindie and it works very nicely- nice job on the design

Thanks Mike

**Comment by mjs513** [comment]
Kris

Quick question.  There is a self test that I could use.  The question I have is when I set the register for self test it has to be in standby.  I then go back to active and read the gyro values? the do a put it back to normal mode?  Just need confirmation or not :)

Mike

**Comment by kriswiner** [comment]
My sketch has the self test implemented. It should be clear there what needs
to be done, I can't remember off the top of my head.

Kris

-----Original Message-----

**Comment by mjs513** [comment]
Hi Kris
I really couldn't find that piece of it in the code.  So I came up with the following quick and dirty:

void selfTest()
{
    FXOS8700CQStandby();

```
writeByte(FXAS21000_ADDRESS, FXAS21000_CTRL_REG0, gyroFSR);
     // Setup the 3 data rate bits, 4:2     

// Disable FIFO, route FIFO and rate threshold interrupts to INT2, enable data ready interrupt, route to INT1
// Active HIGH, push-pull output driver on interrupts
```

 writeByte(FXAS21000_ADDRESS, FXAS21000_CTRL_REG2, 0x0E);
    writeByte(FXAS21000_ADDRESS, FXAS21000_CTRL_REG1, 0x2E);
  readGyroData(gyroCount);
  Serial.print("Gyroscope ");
  Serial.print("Xs: ");
  Serial.print(gyroCount[0]);
  Serial.print(" Ys ");
  Serial.print(gyroCount[01]);
  Serial.print(" Zs: ");
  Serial.println(gyroCount[2]);
}

The 2E in register1 is based on Tabl45.  It sets ST to 1, odr to 011 (100hz) and 10  (Active-Ready bits - sets to active).  If I did this right it give is telling me the gyro is bad.

**Comment by kriswiner** [comment]
Hi Mike,

I would have to look at this in detail, but a lot of self tests are intended
to apply a known deflection of the silicon levers in the MEMS device and
either compare with what was measured at the factory or compare to some
datasheet standard.

I'd have to look in more detail to know if your gyro failed the self test,
but maybe you can already determine this from your looking.

Another easy way to tell if the gyro is working is simply to look at a raw
gyro data stream while the sensor is sitting still. For the gyro, it should
read tens of counts at 250 dps full scale (or 16000 for small negative
values) If you see 512 repeated without change your gyro is broken.

MEMS sensors are pretty delicate and will literally break (inside) if
subjected to sharp knocks, shocks or even falling from desk height onto a
wood floor (I know!).

Kris

-----Original Message-----

**Comment by mjs513** [comment]
Yeah.  Pretty sure its dead.  The raw data stream is showing all 512's.  I usually don't drop the sensors, I usually connect power to gnd because I can't see ! That's why I usually buy two of at a time.

By the way got it working with my version of Fabio's FreeIMU library using Paul's library and a separate lib for the pressure sensor.  I prefer the way you have it formatted (looks like sbas's and mlwarner's lib).  Its clear on whats going on and easier to change settings.  I also want the ability to change things like FSR and ODR programmatically as opposed to going into the library to change the settings.  

Let me know if you play around with self-test - I will go ahead and close this as an issue.  

Thanks for your help
Mike

**Comment by kriswiner** [comment]
I'll get to the self test eventually; although I thought I had done so
already. I'll take a look today.

Kris

-----Original Message-----
