### ISSUE TITLE
 narrowing conversion of '32768' from 'int' to 'int16_t Error message.

### ISSUE THREAD

**Issue by mjs513** [kriswiner/Teensy_Prop_Shield#4]
Hi Kris,

Tried compiling the sketch for the Teensy3.5 using IDE1.8.3 and TD1.38Beta1.  I started received the following error message:
```
TeensyPropShield:897: error: narrowing conversion of '32768' from 'int' to 'int16_t {aka short int}' inside { } [-Wnarrowing]
   int16_t mag_max[3] = {0x8000, 0x8000, 0x8000}, mag_min[3] = {0x7FFF, 0x7FFF, 0x7FFF}, mag_temp[3] = {0, 0, 0};

TeensyPropShield:897: error: narrowing conversion of '32768' from 'int' to 'int16_t {aka short int}' inside { } [-Wnarrowing]
TeensyPropShield:897: error: narrowing conversion of '32768' from 'int' to 'int16_t {aka short int}' inside { } [-Wnarrowing]
TeensyPropShield:906: error: cannot convert 'int16_t* {aka short int*}' to 'int*' for argument '1' to 'void readMagData(int*)'
   readMagData(mag_temp);
```
So the experimenter I am I changed it to:
`  int mag_max[3] = {0x8000, 0x8000, 0x8000}, mag_min[3] = {0x7FFF, 0x7FFF, 0x7FFF}, mag_temp[3] = {0, 0, 0};`
and received other messages associated with int16 vs int.  I changed things to just ints but probably should have changed them to int32??  or is there a better way.

Mike

**Comment by kriswiner** [comment]
Since these are int16_t numbers you should set max to -32767 and min to
+32767. I have changed this in most of the repositories. Downside of not
using a library is I seem to have missed a few.

**Comment by mjs513** [comment]
Didn't expect such a quick answer.  Will make the change a little later. If I run into problem will let you know.

Thanks
Mike

EDIT:  Made the change.  All is wonderful :)
