### ISSUE TITLE
Not Issue:  Working on converting your sketch to Library

### ISSUE THREAD

**Issue by mjs513** [kriswiner/Teensy_Prop_Shield#5]
Hi Kris

I am working on converting your sketch to library, at least parts of it.  Right now I have it working but still a mess, needs a lot of clean up but am having a problem with yaw.  Doesn't want to rotate through 360.  Stuck between 200 and 250.  Ran your sketch and got same results.  Was wondering if you have some time you can give it a try and let me know if it is my propshield or not.  I can post it on the teensy forum if you prefer.

[Teensy_Prop_Shield.zip](https://github.com/kriswiner/Teensy_Prop_Shield/files/1120786/Teensy_Prop_Shield.zip)
Thanks
Mike

**Comment by kriswiner** [comment]
Did you calibrate the sensors first? If the mag is way out of calibration
you can get these kinds of goofy results.

**Comment by mjs513** [comment]
Yep.  Went through your builtin calibration with both sketches.  Haven't added the option to write to flash yet.   Can give it another try and will let you know.

Edit.  Gave it another try and same thing.  Funny thing is pitch and roll behave normally, its just yaw.

**Comment by mjs513** [comment]
Been debugging the library and for some strange reason the magnetometer just does not want to read the values.  Reading accel and gyro fine?  Have to do some more work I guess.

**Comment by kriswiner** [comment]
It's been quite a while since I used this prop shield. If you really get
stuck I suppose I can dust it off and give it a try myself.

**Comment by mjs513** [comment]
No.  Think one problem was mag min and max in the setup.  I just changed it 7fff max and -7ffff min.  It got better.  At least I see the values for mag change.  Hope this is right.  still have to figure out a few things.  Thanks for the offer of dusting it off, don't think its necessary just yet :)

**Comment by mjs513** [comment]
Hi Kris.  Got it working but I think you magoffset function. Is incorrect. If you set the initial min and Max values +/-32767 you will only get those values and the offsets will always be zero.  Have to do a double check on the scale. 

Mike

**Comment by kriswiner** [comment]
If one sets the min to +32767 the surely at least one value will be less
than this and be the new minimum, vice versa for max. This logic seems to
work for all of my sketches with the MPU9250, BMX055, and LSM9DS1 so I
would be surprised if it doesn't work for freescale's mag but maybe it
isn't int16_t?

**Comment by mjs513** [comment]
ok. my bad. had the signs reversed for min and max.  sorry. set them to
zero and it worked. didn't think about reversing the signs.

**Comment by kriswiner** [comment]
Zero is not a good choice

**Comment by mjs513** [comment]
Fixed it so that max is at -07ff and min is at 7fff.  Works now.  But something strange still going on. Next step I guess.

**Comment by kriswiner** [comment]
I think -32767 in HEX is 0x8001, and 0x7FFF == 32767 is the negative of
0x8001.

I just set the min/max to +/-32767, but if you want to use HEX use 0x8001
for -32767.

-0x07FF has no meaning in two's complement.

**Comment by mjs513** [comment]
Interesting.  I couldn't figure negative hex out.  The online converters don't do that one.  :) One I thought there was some reason you were using hex.  should have just tried it.  

Edit:  Just tried it and it works fine now.  Thanks for your patience.  Now for some clean up.   One interesting thing is that with the lib version I get a rate of about 93hz but with your sketch its about 1678.  Something is way off, must have a typo.

**Comment by mjs513** [comment]
Hi Kris.  Got it all working.  I added a few extra functions to the library:
```
		void setAccelFSR(uint8_t range);
		void setAccelSensitivity(uint16_t range);
		void setAccelODR(uint8_t range);
		void setGyroFSR(uint8_t range);
		void setGyroODR(uint8_t range);
		void setCal(uint8_t range);
		void setSeaPress(float sea_press_inp);
```
I also gave it an option to run the built in calibration or read a cal file formatted using the FreeIMU calibration gui (made modifications accordingly.  I will let you know when I post the lib in case you want to give it a shot.

Thanks for all your help.
Mike
