### ISSUE TITLE
FXOS8700CQ Data Not Always Updating

### ISSUE THREAD

**Issue by mjs513** [kriswiner/Teensy_Prop_Shield#7]
Hi Kris.

Got everything working now including linking it to a couple of processing sketches.  However, I noticed that if the sensor stays stationary for too long the accel/mag data does not update for a couple of seconds.  If I shake it then it starts up again.  Beginning to go through the code again as well as the documentation.  Its like its entering a sleep mode or other mode.  Is this related to the low power mode you mentioned in the readme?  Do recall what has to be changed to keep it in continuous mode in your code?

Thanks
Mike

**Comment by kriswiner** [comment]
Hi Mike,

I don't really remember, but these devices usually have a stillness mode
such that if the accel/gyro detects zero motion for a while it will put the
sensors in low power state, which usually means accel only.

I'd have to take a look at the data sheet to tell which register controls
this.

**Comment by mjs513** [comment]
Ok started out just commenting out the calls to the standby mode and setinterrupts but no luck.  Took a look at Paul's code and some barebone code on nxp website.  That led me to commenting out the code in the accel/mag init routine.  That seemed to be the only diff.  That  did the trick.  Now it continuously streams the data.

Seeing a lot of jitter but I can deal with that one.  Seen that before :)

Thanks for your help.
Mike

Update 1.  Redid the interrupts to enable drdy.  But did it this way:
```
     writeByte(FXOS8700CQ_ADDRESS, FXOS8700CQ_CTRL_REG3, 0x00);          // Push-pull, active low interrupt 
     writeByte(FXOS8700CQ_ADDRESS, FXOS8700CQ_CTRL_REG4, 0x01);          // Enable DRDY interrupt 
     writeByte(FXOS8700CQ_ADDRESS, FXOS8700CQ_CTRL_REG5, 0x01);          // DRDY interrupt routed to INT1 - 
```

**Comment by mjs513** [comment]
Got everything sorted out.  I added a butterworth filter to the accel and magnetometer and noise levels were reduced to acceptable level at the ODRs being used.  Also tested it the FDRM board from NXP and it worked nicely.  Probably should move it to its own GitHub page.  I don't know.

Thanks for everything 
MIke

**Comment by kriswiner** [comment]
Glad you got it all to work. For my work, I use the MPU9250 since in all of
my testing it has been the least jittery and given the best orientation
accuracy. But I know a lot of people are using the prop shield for other
than flying robots, etc.

**Comment by mjs513** [comment]
Really like the 9250 myself.  Have two of your breakout boards which work great.  The best ive seen.  With Brian Taylor 9250 approach can get two of them working at the same time.

Prop shield was a challenge I just could not resist trying to get working the way I wanted it.  

Really appreciate the help.
